spring.application.name=card-tokenization-simulator
jwt.secret=MySuperSecretKeyForJWTSigningThatIsLongEnough123456
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.security.debug=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.security.user.name=dummy
spring.security.user.password=dummy
