spring.application.name=card-service
server.port=8080
jwt.secret=MySuperSecretKeyForJWTSigningThatIsLongEnough123456
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=dev
